// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmW1VxuLAudnndValTDMunLkK6K5Qa_5U',
    appId: '1:596859222091:web:a79d030988cc87a9c675ce',
    messagingSenderId: '596859222091',
    projectId: 'hackerspace-79b82',
    authDomain: 'hackerspace-79b82.firebaseapp.com',
    storageBucket: 'hackerspace-79b82.firebasestorage.app',
    measurementId: 'G-HQYB8M8MDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoNKJFr0IjKxzJ01VaN396OzxhQwOhuEw',
    appId: '1:596859222091:android:30f302627f43f501c675ce',
    messagingSenderId: '596859222091',
    projectId: 'hackerspace-79b82',
    storageBucket: 'hackerspace-79b82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyhPHROkA4mmedJuZ988QouiFo5f_t84',
    appId: '1:596859222091:ios:62b10f36b54051f7c675ce',
    messagingSenderId: '596859222091',
    projectId: 'hackerspace-79b82',
    storageBucket: 'hackerspace-79b82.firebasestorage.app',
    iosClientId: '596859222091-fkj0g9k62s1hdb4v4d6737iouif2h5b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackerspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyhPHROkA4mmedJuZ988QouiFo5f_t84',
    appId: '1:596859222091:ios:62b10f36b54051f7c675ce',
    messagingSenderId: '596859222091',
    projectId: 'hackerspace-79b82',
    storageBucket: 'hackerspace-79b82.firebasestorage.app',
    iosClientId: '596859222091-fkj0g9k62s1hdb4v4d6737iouif2h5b6.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackerspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmW1VxuLAudnndValTDMunLkK6K5Qa_5U',
    appId: '1:596859222091:web:dfac8d9310968d92c675ce',
    messagingSenderId: '596859222091',
    projectId: 'hackerspace-79b82',
    authDomain: 'hackerspace-79b82.firebaseapp.com',
    storageBucket: 'hackerspace-79b82.firebasestorage.app',
    measurementId: 'G-PGMT9HTGK6',
  );

}